// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GroupChat = __t.object("GroupChat", {
  id: __t.u64(),
  name: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type GroupChat = __Infer<typeof GroupChat>;

export const GroupMember = __t.object("GroupMember", {
  groupId: __t.u64(),
  memberId: __t.identity(),
});
export type GroupMember = __Infer<typeof GroupMember>;

export const Message = __t.object("Message", {
  sender: __t.identity(),
  roomType: __t.string(),
  roomId: __t.string(),
  body: __t.string(),
  sent: __t.timestamp(),
  parentId: __t.option(__t.u64()),
});
export type Message = __Infer<typeof Message>;

export const PrivateChat = __t.object("PrivateChat", {
  roomId: __t.string(),
  participantA: __t.identity(),
  participantB: __t.identity(),
  lastMessageAt: __t.timestamp(),
});
export type PrivateChat = __Infer<typeof PrivateChat>;

export const Reaction = __t.object("Reaction", {
  messageSent: __t.timestamp(),
  messageSender: __t.identity(),
  sender: __t.identity(),
  emoji: __t.string(),
});
export type Reaction = __Infer<typeof Reaction>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.string(),
  handle: __t.string(),
  avatarUrl: __t.option(__t.string()),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type User = __Infer<typeof User>;

