// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReactionReducer from "../add_reaction_reducer";
import CreateGroupReducer from "../create_group_reducer";
import CreatePrivateChatReducer from "../create_private_chat_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import EditMessageReducer from "../edit_message_reducer";
import JoinGroupReducer from "../join_group_reducer";
import LeaveGroupReducer from "../leave_group_reducer";
import RemoveReactionReducer from "../remove_reaction_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetAvatarUrlReducer from "../set_avatar_url_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";

export type AddReactionParams = __Infer<typeof AddReactionReducer>;
export type CreateGroupParams = __Infer<typeof CreateGroupReducer>;
export type CreatePrivateChatParams = __Infer<typeof CreatePrivateChatReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type JoinGroupParams = __Infer<typeof JoinGroupReducer>;
export type LeaveGroupParams = __Infer<typeof LeaveGroupReducer>;
export type RemoveReactionParams = __Infer<typeof RemoveReactionReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetAvatarUrlParams = __Infer<typeof SetAvatarUrlReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;

