// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sender: __t.identity(),
  roomType: __t.string().name("room_type"),
  roomId: __t.string().name("room_id"),
  body: __t.string(),
  sent: __t.timestamp(),
  parentId: __t.option(__t.u64()).name("parent_id"),
});
